### ISSUE TITLE
Email settings

### ISSUE THREAD

**Issue by ctuxboy** [jflepp/PicoMailForms#2]
Hello,

Thx for the help [how installing](https://github.com/jflepp/PicoMailForms/issues/1) your plugin with composer, however i asked if it **config/config.yml** is the right place for the mail-settings (i think yes!), without answer:

```
Mail:
    SenderName: Christophe
    Host: smtp.gmail.com
    UserName: ***@gmail.com
    Password: ***
    Port: 465
    OperatorMail: c.***@gmail.com
```

Here you can see and test my [test-form](https://pico.webkusthosting.be/mail) if you want.
Trying with the gmail settings and also with the settings of my hosting company, and playing with some settings but nothing works, both outgoing-mail settings shows an error, so the mail don't send the form.

_An error occured while sending your message. Please contact the site administrator._

Sorry about my beginners questions, i hope you can help me further how solve this problem.
